mysql:
  image: mariadb:10.0
  environment:
    MYSQL_ROOT_PASSWORD: dockerimage
  volumes:
    - /data/mysql:/var/lib/mysql
mongodb:
  image: mongo:3.0
  volumes:
    - /data/mongo:/data/db
redis:
  image: redis:3.0
  volumes:
    - /data/redis:/data
memcached:
  image: memcached:1.4
scheduler:
  image: shiningray/teapoy2
mailman:
  image: shiningray/teapoy2
puma:
  image: shiningray/teapoy2
  environment:
    REDIS_URL: redis://redis
  links:
    - mysql
    - mongodb
    - redis
    - memcached
  volumes:
    - /data/teapoy2:/data
  expose:
    - 3001:3000
nginx:
  image: dockerfile/nginx
  links:
    - puma
  expose:
    - 80
    - 443
