mysql:
  image: mariadb:10.0
  environment:
    MYSQL_ROOT_PASSWORD: dockerimage
  volumes:
    - vendor/data/mysql:/var/lib/mysql
mongodb:
  image: mongo:3.0
  volumes:
    - vendor/data/mongo:/data/db
redis:
  image: redis:3.0
  volumes:
    - vendor/data/redis:/data
memcached:
  image: memcached:1.4
scheduler:
  image: rails:4.2
mailman:
  image: rails:4.2
puma:
  image: yandy0725/railsdev:latest
  environment:
    REDIS_URL: redis://redis
  links:
    - mysql
    - mongodb
    - redis
    - memcached
  volumes:
    - .:/data
  expose:
    - 3001:3000
