rails: &rails
  image: shiningray/teapoy2
  environment:
    RAILS_ENV: production
    REDIS_URL: redis://redis
    APP_ROOT: /app
    PUMA_PORT: 3000
  links:
    - mysql
    - mongodb
    - redis
    - memcached
  working_dir: /app

mysql:
  image: mariadb:10.0
  environment:
    MYSQL_DATABASE: teapoy2
    MYSQL_USER: teapoy
    MYSQL_PASSWORD: teapoy
    MYSQL_ROOT_PASSWORD: dockerimage
  volumes:
    - /data/mysql:/var/lib/mysql
mongodb:
  image: mongo:3.0
  volumes:
    - /data/mongo:/data/db
redis:
  image: redis:3.0
  volumes:
    - /data/redis:/data
memcached:
  image: memcached:1.4
scheduler:
  <<: *rails
mailman:
  <<: *rails
sidekiq:
  <<: *rails
puma:
  <<: *rails
  expose:
    - 3000:3000
  command: bundle exec puma -t 8:32 -w 3 -b tcp://0.0.0.0:3000 --preload --daemon

railsdev:
  <<: *rails
  volumes:
    - .:/app
  command: bundle exec rails c production
  stdin_open: true
  tty: true

nginx:
  image: nginx
  links:
    - scheduler
    - mailman
    - puma
  expose:
    - 80
    - 443
