development:
  qiniu:
    access_key: <%= ENV['qiniu_access_key'] %>
    secret_key: <%= ENV['qiniu_secret_key'] %>
    bucket: <%= ENV['qiniu_bucket'] %>
    bucket_domain: <%= ENV['qiniu_domain'] %>
    protocol: http
  mem_cache:
    - 'localhost:11211'
    -
      compress: true
  smtp_settings:
    address: 'localhost'
    port: 25
    domain: 'bling0.com'
    enable_starttls_auto: false
  secret_key_base: 58b4444402f3fbceb25ffa10e20d0a99c65c75ca4ff1d66488bc2814650918027cb727947327a6f68571726457f7b43da5cc4806e75dcf8351dc14291f3f36c1
test:
  qiniu:
    access_key: 4UNmiLDvEjaG78a_SMM3RBib_O348nAc_BuzfBwD
    secret_key: o57Xp4NlbpfLEz28N_3K3CNqXCLki_w0y9A6mQ4I
    bucket: anti-hulk
    bucket_domain: 7xivqf.com1.z0.glb.clouddn.com
    protocol: http
  secret_key_base: 58b4444402f3fbceb25ffa10e20d0a99c65c75ca4ff1d66488bc2814650918027cb727947327a6f68571726457f7b43da5cc4806e75dcf8351dc14291f3f36c1
production:
  secret_key_base: 58b4444402f3fbceb25ffa10e20d0a99c65c75ca4ff1d66488bc2814650918027cb727947327a6f68571726457f7b43da5cc4806e75dcf8351dc14291f3f36c1
  qiniu:
    access_key: <%= ENV['qiniu_access_key'] %>
    secret_key: <%= ENV['qiniu_secret_key'] %>
    bucket: <%= ENV['qiniu_bucket'] %>
    bucket_domain: <%= ENV['qiniu_domain'] %>
    protocol: http
