require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChangeLogsController do

  # This should return the minimal set of attributes required to create a valid
  # ChangeLog. As you add validations to ChangeLog, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChangeLogsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all change_logs as @change_logs" do
      change_log = ChangeLog.create! valid_attributes
      get :index, {}, valid_session
      assigns(:change_logs).should eq([change_log])
    end
  end

  describe "GET show" do
    it "assigns the requested change_log as @change_log" do
      change_log = ChangeLog.create! valid_attributes
      get :show, {:id => change_log.to_param}, valid_session
      assigns(:change_log).should eq(change_log)
    end
  end

  describe "GET new" do
    it "assigns a new change_log as @change_log" do
      get :new, {}, valid_session
      assigns(:change_log).should be_a_new(ChangeLog)
    end
  end

  describe "GET edit" do
    it "assigns the requested change_log as @change_log" do
      change_log = ChangeLog.create! valid_attributes
      get :edit, {:id => change_log.to_param}, valid_session
      assigns(:change_log).should eq(change_log)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChangeLog" do
        expect {
          post :create, {:change_log => valid_attributes}, valid_session
        }.to change(ChangeLog, :count).by(1)
      end

      it "assigns a newly created change_log as @change_log" do
        post :create, {:change_log => valid_attributes}, valid_session
        assigns(:change_log).should be_a(ChangeLog)
        assigns(:change_log).should be_persisted
      end

      it "redirects to the created change_log" do
        post :create, {:change_log => valid_attributes}, valid_session
        response.should redirect_to(ChangeLog.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved change_log as @change_log" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChangeLog.any_instance.stub(:save).and_return(false)
        post :create, {:change_log => {  }}, valid_session
        assigns(:change_log).should be_a_new(ChangeLog)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChangeLog.any_instance.stub(:save).and_return(false)
        post :create, {:change_log => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested change_log" do
        change_log = ChangeLog.create! valid_attributes
        # Assuming there are no other change_logs in the database, this
        # specifies that the ChangeLog created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ChangeLog.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => change_log.to_param, :change_log => { "these" => "params" }}, valid_session
      end

      it "assigns the requested change_log as @change_log" do
        change_log = ChangeLog.create! valid_attributes
        put :update, {:id => change_log.to_param, :change_log => valid_attributes}, valid_session
        assigns(:change_log).should eq(change_log)
      end

      it "redirects to the change_log" do
        change_log = ChangeLog.create! valid_attributes
        put :update, {:id => change_log.to_param, :change_log => valid_attributes}, valid_session
        response.should redirect_to(change_log)
      end
    end

    describe "with invalid params" do
      it "assigns the change_log as @change_log" do
        change_log = ChangeLog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChangeLog.any_instance.stub(:save).and_return(false)
        put :update, {:id => change_log.to_param, :change_log => {  }}, valid_session
        assigns(:change_log).should eq(change_log)
      end

      it "re-renders the 'edit' template" do
        change_log = ChangeLog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChangeLog.any_instance.stub(:save).and_return(false)
        put :update, {:id => change_log.to_param, :change_log => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested change_log" do
      change_log = ChangeLog.create! valid_attributes
      expect {
        delete :destroy, {:id => change_log.to_param}, valid_session
      }.to change(ChangeLog, :count).by(-1)
    end

    it "redirects to the change_logs list" do
      change_log = ChangeLog.create! valid_attributes
      delete :destroy, {:id => change_log.to_param}, valid_session
      response.should redirect_to(change_logs_url)
    end
  end

end
